name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install dependencies
      run: |
          sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
          sudo apt-get update -y -qq
          sudo apt-get install libsdl2-dev
    - name: Build
      run: cargo build --verbose

  build_chip_target:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install target
      run: rustup target add thumbv6m-none-eabi
    - name: Build target
      working-directory: ./main
      run: cargo build --verbose

  build_chip_target:
    runs-on: ubuntu-latest
    - name: Run tests
      working-directory: ./tests
      run: cargo test --verbose
